version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - tintulip/dali-platform-dev-laptops

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - tintulip/dali-platform-dev-laptops